### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#1202]
We want to focus on updating our documentation in the top level GitHub repo, within the packages, and on our Zowe docs page.

The issues for this epic include the following:

- [ ] #1060 Top Level Readme updates
- [ ] #1182 New functionalities from Zowe Explorer
- [ ] Zowe Doc-site updates - in connection to above item
- [ ] #408 Theia docs
- [ ] Zowe Explorer Guidelines
     - #950 Contributing Guidelines
     - #633 Getting Started as a developer
- [ ] The docs part in our repo: https://github.com/zowe/vscode-extension-for-zowe/tree/master/docs

**Comment by jellypuno** [comment]
I have some other general notes for docs:
- Documentation (Doc-site and wiki)
   - What are the available APIs
   - Best Practices?
   - Extending Zowe Explorer
   - Contributing Guidelines
     - Coding Standards
     - Testing
   - Developer: Preparing for a release
- Blogs
- Tutorial Videos
   - What are the current features of Zowe Explorer
