### ISSUE TITLE
Publish documentation that supports the Zowe Explorer Conformance Criteria

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#1276]
We need to document the code samples to support the Zowe Explorer Conformance Criteria: https://ent.box.com/s/hqzfsia30z09hsjo8gj40kunhjaw9ebj

The issues for this epic include the following:

- [ ] Extension uses `IApiRegisterClient` to register the new data provider during activation #1283. https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Extending.md#zowe-explorer-extender-api
- [ ] If the extension is adding new commands to the context menu, it adheres to the Zowe Explorer-provided contextual string format #1279. https://github.com/zowe/vscode-extension-for-zowe/wiki/Working-with-Context-Menus-and-Icons-in-Zowe-Explorer
- [ ] Extension follows the VS Code configuration property name format as indicated in the API documentation #1263 
- [ ] Extension follows the Zowe Explorer error messaging format #388

**Comment by phaumer** [comment]
@crawr we already have an Epic for compliance, which is #837 Should we close this as a duplicate?

**Comment by crawr** [comment]
closing in favor of #672
