### ISSUE TITLE
23PI2 Planning

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#2206]
## 23PI2 Key Dates

Kickoff - 4/3/23, 9 am ET
[PI Planning Day 1](https://lists.openmainframeproject.org/g/zowe-dev/viewevent?eventid=1895083&calstart=2023-04-26) - 4/26/23, 8 am - 11 am ET
[ZE Planning Breakout](https://lists.openmainframeproject.org/g/zowe-dev/viewevent?repeatid=39371&eventid=1778820&calstart=2023-04-27) - 4/27/23, 11 am ET
[PI Planning Day 3](https://lists.openmainframeproject.org/g/zowe-dev/viewevent?eventid=1895087&calstart=2023-04-28) - 4/28/23, 9 am - 11 am ET

# Zowe Explorer VS Code extension

## v3 Pre-Release early availability

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2072
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1910
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/2109
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/1985
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2148
- [ ] [Stretch] https://github.com/zowe/vscode-extension-for-zowe/issues/2078
- [ ] [Stretch] https://github.com/zowe/vscode-extension-for-zowe/issues/2077

#### *Enhancements*

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2212
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/1667
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2208
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1425
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/2113
- [ ] [Investigation] https://github.com/zowe/vscode-extension-for-zowe/issues/2252 (SSO & MFA)
- [ ] [Stretch] https://github.com/zowe/vscode-extension-for-zowe/issues/2207

#### *Bugs*

- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/1926
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/1625
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2166
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2211
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1897
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2251

#### *Tech Debt*

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2172
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/2214
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/2253
- [ ] [Stretch] https://github.com/zowe/vscode-extension-for-zowe/issues/2063
- [ ] [Stretch] https://github.com/zowe/vscode-extension-for-zowe/issues/2103

## Golden CII Badge

- [ ] [Make sure internal and external documentation meet the CII Badge standard.](https://github.com/zowe/vscode-extension-for-zowe/issues/1966)

### Helpful links for CII Badge criteria:
Passing: https://bestpractices.coreinfrastructure.org/en/criteria/0
Silver: https://bestpractices.coreinfrastructure.org/en/criteria/1
Gold: https://bestpractices.coreinfrastructure.org/en/criteria/2

# CICS VS Code extension

- [ ] https://github.com/zowe/vscode-extension-for-cics/issues/324

# Roadmap

## COMPLETED [Updating GUI to use other types of notifications vs all pop ups](https://github.com/zowe/vscode-extension-for-zowe/issues/1517)

- *What problem are you solving?*
  - Users would like to see less pop up notifications from Zowe Explorer to lessen the distractions that they cause in VS Code.
- *What are you doing to solve it?
  - Assess the types of notifications in place and decide how to proceed.
  - Implement the decided plan of action.
- *When do you plan to start the work?*
  - 22Q3
- *When do you plan to deliver the solution?*
  - 23Q2

## [v3 Pre-Release availability](https://github.com/zowe/vscode-extension-for-zowe/issues/2070)

- *What problem are you solving?*
  - Extenders will need to be aware of breaking changes in the upcoming major release of 3.0.0.
- *What are you doing to solve it?*
  - Publish a pre-release of v3 with documentation of breaking changes so Extenders will be able to begin their adoption early.
- *When do you plan to start the work?*
  - Work has already begun from pre-planning in the 2nd half of last year and implementation began at the beginning of this year.
- *When do you plan to deliver the solution?*
  - 23Q3 

## [Add more functionality to the Jobs tree view](https://github.com/zowe/vscode-extension-for-zowe/issues/1597)

- *What problem are you solving?*
  - Users would like a comparable experience working with JES files, Zowe Explorer doesn't have a lot of functionality in that tree compared to others.
- *What are you doing to solve it?*
  - Add more functionality to jobs in the tree, ie. local sorting, filtering, and more.
- *When do you plan to start the work?*
  - 23Q1
- *When do you plan to deliver the solution?*
  - 23Q4

## [Improve error handling](https://github.com/zowe/vscode-extension-for-zowe/issues/1982)

- *What problem are you solving?*
  - Users would like error messages returned to be relevant to the error encountered and describe the issue clearly.
- *What are you doing to solve it?*
  - Make sure all errors are being handled appropriately and make sure the error message returned is helpful and understandable to the user.
- *When do you plan to start the work?*
  - 23Q1
- *When do you plan to deliver the solution?*
  - 23Q4
