### ISSUE TITLE
23PI3 Planning

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#2357]
## 23PI2 Key Dates

[Community planning doc](https://github.com/zowe/community/blob/master/Project%20Management/PI%20Planning/23PI3%20Planning/PI%20Planning%20Preparation%20by%20Squad/Zowe%20Explorer%20Squad%20-%2023PI3%20Objectives.md)

[Kickoff](https://lists.openmainframeproject.org/g/zowe-dev/viewevent?eventid=1926496) - 7/11 @ 10am
Planning - 2023/07/25 - 2023/07/31
- Wednesday, July 26 - Opening ([Day 1](https://lists.openmainframeproject.org/g/zowe-dev/viewevent?eventid=1991262)) 8 am - 12 pm ET
- Wednesday, July 26 - Breakout ([Day 2](https://lists.openmainframeproject.org/g/zowe-dev/viewevent?eventid=1991158&calstart=2023-07-26)) - 11 am - 12 pm ET
- Friday, July 28 - Final Readouts ([Day 3](https://lists.openmainframeproject.org/g/zowe-dev/viewevent?eventid=1991265)) 9 am - 12 pm ET

Sprint 1 - 2023/08/01 - 2023/08/14 (Innovation Sprint)
Sprint 2 - 2023/08/15 - 2023/08/28
Sprint 3 - 2023/08/29 - 2023/09/11
Sprint 4 - 2023/09/12 - 2023/09/25
Sprint 5 - 2023/09/26 - 2023/10/09
Sprint 6 - 2023/10/10 - 2023/10/23

Scheduled Releases during PI:
- v2.11.0 - GA 2023/09/11
- v2.12.0 - GA 2023/10/23
- v1.28.5 - GA 2023/10/2

# Zowe Explorer Squad - 23PI3 - (2023/08/01 - 2023/10/23)

### v3 Pre-Release early availability

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2360
- [x] Write v3 pre-release blog with updates to users and extenders about breaking changes
- [ ] Decide our Big WOWs for v3 per our [discussion](https://github.com/zowe/vscode-extension-for-zowe/discussions/2391#discussioncomment-6552494)
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/1326
- [ ] [STRETCH] https://github.com/zowe/vscode-extension-for-zowe/issues/2109
- [ ] [STRETCH] https://github.com/zowe/vscode-extension-for-zowe/issues/1985

### Add more functionality to the Jobs tree view [🔗 ](https://github.com/zowe/vscode-extension-for-zowe/issues/1597)

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2257
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/2256
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/1685 - DEFERRED
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1951

### Improve error handling [🔗 ](https://github.com/zowe/vscode-extension-for-zowe/issues/1982)

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1625

### Improve experience for using API ML sessions in Zowe Explorer [🔗 ](https://github.com/zowe/vscode-extension-for-zowe/issues/2252)

- [ ] [STRETCH] https://github.com/zowe/vscode-extension-for-zowe/issues/2261
- [ ] [STRETCH] https://github.com/zowe/vscode-extension-for-zowe/issues/2259

#### Keytar shim in VSC removal in Aug release 

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2348
- [x] Write blog with updates to users and extenders about new credential manager

#### High Priority bugs 

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1926
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/2219
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2335

#### Enhancements

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2254
- [ ] [Stretch] https://github.com/zowe/vscode-extension-for-zowe/issues/2399
- [ ] [Stretch] https://github.com/zowe/vscode-extension-for-zowe/issues/1667
- [ ] [Stretch] https://github.com/zowe/vscode-extension-for-zowe/issues/2207

#### Golden CII Badge

- [ ] [Make sure internal and external documentation meet the CII Badge standard.](https://github.com/zowe/vscode-extension-for-zowe/issues/1966)
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/2400

##### Helpful links for CII Badge criteria:
Passing: https://bestpractices.coreinfrastructure.org/en/criteria/0
Silver: https://bestpractices.coreinfrastructure.org/en/criteria/1
Gold: https://bestpractices.coreinfrastructure.org/en/criteria/2

### zFTP VS Code extension

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2350

### CICS VS Code extension

- [x] https://github.com/zowe/vscode-extension-for-cics/issues/324
- [ ] Complete move to [cics-for-zowe-client repository](https://github.com/zowe/cics-for-zowe-client) with CLI plugin and be publish ready

### Kubernetes Credential Manager Plugin

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/2381
- [x] https://github.com/zowe/zowe-cli-secrets-for-kubernetes/issues/19

# Roadmap

## [v3 Pre-Release availability](https://github.com/zowe/vscode-extension-for-zowe/issues/2070)

- *What problem are you solving?*
  - Extenders will need to be aware of breaking changes in the upcoming major release of 3.0.0.
- *What are you doing to solve it?*
  - Publish a pre-release of v3 with documentation of breaking changes so Extenders will be able to begin their adoption early.
- *When do you plan to start the work?*
  - Work has already begun from pre-planning in the 2nd half of last year and implementation began at the beginning of this year.
- *When do you plan to deliver the solution?*
  - 23Q3 

## [Add more functionality to the Jobs tree view](https://github.com/zowe/vscode-extension-for-zowe/issues/1597)

- *What problem are you solving?*
  - Users would like a comparable experience working with JES files, Zowe Explorer doesn't have a lot of functionality in that tree compared to others.
- *What are you doing to solve it?*
  - Add more functionality to jobs in the tree, ie. local sorting, filtering, and more.
- *When do you plan to start the work?*
  - 23Q1
- *When do you plan to deliver the solution?*
  - 23Q4

## [Improve error handling](https://github.com/zowe/vscode-extension-for-zowe/issues/1982)

- *What problem are you solving?*
  - Users would like error messages returned to be relevant to the error encountered and describe the issue clearly.
- *What are you doing to solve it?*
  - Make sure all errors are being handled appropriately and make sure the error message returned is helpful and understandable to the user.
- *When do you plan to start the work?*
  - 23Q1
- *When do you plan to deliver the solution?*
  - 23Q4

## [Improve experience for using API ML sessions in Zowe Explorer](https://github.com/zowe/vscode-extension-for-zowe/issues/2252)

- *What problem are you solving?*
  - Many users of Zowe Explorer aren't familiar with or are unaware of authentication methods supported by Zowe Explorer, like token authentication, SSO, & MFA. 
- *What are you doing to solve it?
  - For users of the API ML with SSO and MFA, there are enhancements we could make to provide a more first-class experience.
- *When do you plan to start the work?*
  - 23Q3
- *When do you plan to deliver the solution?*
  - 24Q1
