### ISSUE TITLE
v3 pre-release UX cleanup

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#2360]
```[tasklist]
### Tasks
- [x] Change right-click menu item "Update Profile" to "Edit Config File" or similar.
- [x] If user had v1 profiles, on creation remove "Edit config" option in quickpick.
- [ ] Go through README's and other docs on next branch that may need updating, removing mentions of v1 profiles, etc.
- [ ] ~Feedback 👉🏻 DS Template setting to be pulled out of history that is no longer in settings in v3 and keep in settings that can be shared via workspace~ creating it's own [issue](https://github.com/zowe/vscode-extension-for-zowe/issues/2389) for the epic
```
