### ISSUE TITLE
Removal of launch and docs related to Theia 

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#2726]
Removal of Theia support in v3 launches, documentation, and others
Questions:
- init.unit.test.ts line 298, 307, & 373; are these test needing rename or removal?
- KeytarCredentialManager.ts line 208 workaround, is comment needing removal or is there more to it?

```[tasklist]
### Tasks
- [ ] launch.json Theia launch
- [ ] READMEs; top level & ZE theia mentions
- [ ] ZE package.json "test:theia" item
- [ ] init.unit.test.ts line 298, 307, 373
- [ ] ProfilesCache.getProfileInfo() theia parameter
- [ ] KeytarCredentialManager.ts line 208
```

**Comment by JillieBeanSim** [comment]
added removal of launch in https://github.com/zowe/vscode-extension-for-zowe/pull/2729
