### ISSUE TITLE
Improve experience working with USS

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#823]
We've had a number of issues that deal with USS. We want to focus on resolving these during the next PI.

The issues for this epic include the following: 
- [x] #187 Default to LF (vs CRLF) when editing USS files
- [ ] #458 Opening files. Download new copy or reuse local?
- [ ] #483 USS - File Tree should keep Node state when you reload it
- [x] #563 USS Rename - File Opening flow
- [x] #567 USS Folder Rename hiccup? (Should be rechecked after merge [#961](https://github.com/zowe/vscode-extension-for-zowe/pull/961) and [#957](https://github.com/zowe/vscode-extension-for-zowe/pull/957))
- [x] #650 USS Tree collapses after folder rename (@JillieBeanSim has claimed this issue. Also partially solved by [PR #957](https://github.com/zowe/vscode-extension-for-zowe/pull/957))
- [x] #673 USS Tree collapses when creating a New File or Directory (Closed because similar to [#650](https://github.com/zowe/vscode-extension-for-zowe/issues/650))
- [ ] #750 Follow symlinks in USS tree
- [x] #755 eTag error encountered when saving a file in root of tree (USS)
- [x] #757 Renaming a USS directory changes the tree structure
- [x] #769 refreshing USS file list under a directory?
- [x] #782 Unable to edit ASCII file in USS
- [ ] #793 USS File in favorites can fail on save
- [x] #806 Data on USS files is cache'd locally and not cleared, so opened/closed files don't show correct content in some scenarios

**Comment by JillieBeanSim** [comment]
all items have been completed or cancelled, closing
