### ISSUE TITLE
Support SSO for API ML in Zowe Explorer

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#901]
**Is your feature request related to a problem? Please describe.**

As a user, I'd like to be able to use Zowe Explorer with a base profile that I have created elsewhere and/or be able to create a base profile in Zowe Explorer and have it propagated elsewhere. This supports the effort for better security and access that is central to the Zowe project as a whole. 

**Describe the solution you'd like**

I'd like to be able to select a base profile from a drop-down when I create a new profile. The creation flow should remain the same if I just want to create a normal zOSMF profile as before, but should have additional parameters for the base profile. Additionally, it would be nice to have the prompting for authorization as part of the flow, if I do not already have a token created elsewhere. 

**Issues**

- [ ] #912 Enable Zowe Explorer for read base profiles/tokens authorized in CLI
- [ ] #913 Implement new workflow for creating base profiles
- [ ] #914 Implement prompting for token/credentials (SSO for API ML)

**Additional context**

Possible flow: 
![image](https://user-images.githubusercontent.com/38981509/85716662-fd835080-b6ec-11ea-9f14-345a7cc2aff6.png)

Resources about the API ML:
https://medium.com/@eugene.johnston/using-tokens-in-the-zowe-cli-3b221f09ec5b

https://medium.com/zowe/token-handling-in-zowe-cli-plug-ins-7be0447fc49f

**Comment by jellypuno** [comment]
![MVP for 20PI3](https://user-images.githubusercontent.com/45042840/88913070-93684900-d260-11ea-89b6-399172c3ebb2.jpg)

**Comment by zdmullen** [comment]
Thanks, @jellypuno for posting the diagram.

**Comment by jellypuno** [comment]
this has already been implemented
