### ISSUE TITLE
Continued Enhancement to User Experience

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#902]
**Is your feature request related to a problem? Please describe.**

As a result of extensive use by folks in the COBOL Learning Program and others, a batch of issues has been compiled by John with respect to the overall user experience. Several of these concern profiles, in continuation from the epic we had in the previous PI. 

**Describe the solution you'd like**

Here's a list of the associated issues that John has already opened for us, along with a couple of others:

- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/861 Guide Users to Create Connections
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/862 Match Terminology to Tasks of Creating Connecitons
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/863 Simplifying the handling of SSL Certificate Validation (a.k.a., Reject Unauthorized)
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/864 Allow Editing Search Strings 
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/865 Eliminate need to click a menu-item to create a new search.
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/866 Support Search/Filter on Data Sets without High Level Qualifier 
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/867 Support More Flexibility in Search/Filter 
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/868 Allow searching for members
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/869 Make it easier to show job details when a user runs submits a JCL job data set.
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/870 Enhance interface for jobs that take a long time to run 
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/872  Change label from No datasets found to No members found
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/873 Repeat Icon Actions in Context Menu
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/876 Support File Diff Comparisins from in ZE
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/877 Put Save in ZE Menus or buttons
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/878 Make it easier to work with downloaded files and data sets
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/885 Simplify text in dialog when creating a profile 
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/891 Icons for individual trees 

**Additional context**

 Some of these have been noted in other issues, so it will be important just to track which coordinating issues are resolved when we address these.
