### ISSUE TITLE
Enhance the data set user experience

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#903]
**Is your feature request related to a problem? Please describe.**

Users should have a few more options when it comes to creating and working with data sets. They should be able to leverage the new "allocate like" REST call of zOSMF to create a new data set with the same attributes as an existing one. An extension of this ability would be to provide users with the capability to create templates where they can set attributes for data sets. Below is a list of issues connected to improving this experience under the solution section.

**Describe the solution you'd like**

- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/866 Support Search/Filter on Data Sets without High Level Qualifier
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/868 Allow searching for members
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/871 Support duplicating data sets
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/874 Enhance the Copying of Data Set Members
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/884 Make it easier to edit datasets and files with num mode on
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/904 Implement the "like data set capability available from zOSMF API

**Additional context**

Info about the allocate like REST call in zOS

https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.izua700/IZUHPINFO_API_CreateDataSet.htm

**Comment by katelynienaber** [comment]
Linked PR #920 because, while it is not explicitly listed here in the goals, it is intended to enhance the data set user experience.

**Comment by zFernand0** [comment]
Please don't tag Epics in every PR

**Comment by JillieBeanSim** [comment]
Closing this issue with epic label.  Last open item has been added to Low Priority column
